[build]
  base    = "frontend"
  command = "npm install && export CI=false && node ./node_modules/react-scripts/bin/react-scripts.js build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  CI = "false"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
